{% set name = "mamba_gator" %}
{% set version = "6.0.2" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: faa5ff346346a4895ee3c76a5b820d42a42a40cf332a3ddc6f1c6c6a56372242

build:
  noarch: python
  number: {{ build_number }}

outputs:
  - name: {{ name|lower }}
    build:
      number: {{ build_number }}
      noarch: python
      entry_points:
        - gator = mamba_gator.navigator.main:main
    script: build_base.sh
    requirements:
      build:
        - nodejs >=12.0.0,!=13,!=15,!=17,<18.0.0
      host:
        - python {{ python_min }}
        - pip
        - hatchling >=1.9.0
        - hatch-jupyter-builder
        - jupyterlab >=3.6.7,<5
        - jupyter-packaging >=0.7.9,<0.8.0
      run:
        - python >={{ python_min }}
        - jupyter_client
        - jupyterlab_server >=2.0.0,<3.0.0
        - packaging
        - tornado
        - traitlets

    test:
      imports:
        - mamba_gator
      requires:
        - pip
        - jupyterlab >=3.6.7,<5
        - python {{ python_min }}
      commands:
        - pip check
        - jupyter server extension list 2>&1 | grep -ie "mamba_gator.*OK"
        - jupyter labextension list 2>&1 | grep -ie "@mamba-org/gator-lab.*OK"
        - gator --help
  # Provide package with old name for update
  - name: jupyter_conda
    build:
      number: {{ build_number }}
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}

about:
  home: https://github.com/mamba-org/gator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda environment and package access extension from within Jupyter

extra:
  feedstock-name: jupyter_conda
  recipe-maintainers:
    - fcollonval
    - dbast
