{% set name = "mamba_gator" %}
{% set version = "4.0.0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a6ae3f0059d782e977dfaefaa636db50f9438fa8bdaf75857b9dc85681c29a5

build:
  noarch: python
  number: {{ build_number }}

outputs:
  - name: {{ name|lower }}
    build:
      number: {{ build_number }}
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python >=3.5
        - pip
      run:
        - python >=3.5
        - jupyterlab_server
        - notebook >=4.3.1
        - packaging
        - requests
    test:
      imports:
        - mamba_gator
      requires:
        - pip
      commands:
        - pip check
        - gator --help
  # Provide package with old name for update
  - name: jupyter_conda  
    build:
      number: {{ build_number }}
      noarch: generic    
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}

about:
  home: https://github.com/mamba-org/gator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda environment and package access extension from within Jupyter

extra:
  feedstock-name: jupyter_conda
  recipe-maintainers:
    - fcollonval
    - dbast
