{% set name = "jupyter_conda" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 574a647b7accf325daae56d80b681e4db6a60da02d69e83d44089eb1f4bc7a1e

build:
  skip: True  # [py2k]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - notebook >=4.3.1
    - nb_conda_kernels >=2.0.0
    - packaging
    - requests

test:
  imports:
    - jupyter_conda

about:
  home: https://github.com/fcollonval/jupyter_conda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda environment and package access extension from within Jupyter

extra:
  recipe-maintainers:
    - fcollonval
    - dbast
